jobs:
  - script: >
      multibranchPipelineJob('simple-java-app') {
        displayName('simple-java-app')

        branchSources {
          branchSource {
            source {
              github {
                id('simple-java-app')
                repoOwner('sandip84')
                repository('simple-java-maven-app')
<<<<<<< HEAD
                //credentialsId('github-token')
=======
                repositoryUrl('https://github.com/sandip84/simple-java-maven-app.git')
                configuredByUrl(true)
                # credentialsId('github-token')
>>>>>>> 9b8df9c (added jcasc folder)

                // Build PRs only
                buildOriginBranch(false)
                buildOriginBranchWithPR(false)
                buildOriginPRMerge(true)
                buildOriginPRHead(true)
              }
            }
          }
        }

        orphanedItemStrategy {
          discardOldItems {
            numToKeep(10)
          }
        }

        triggers {
          periodicFolderTrigger {
            interval('1d')
          }
        }
      }
